// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htvbbyoghtoionbvzekw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dmJieW9naHRvaW9uYnZ6ZWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjA0MjMsImV4cCI6MjA3MjAzNjQyM30.CzfqJUnK-OMgo1CFtgIgLk1rB1S84OaZZGnkQOL4LKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});